name: RSS Update

on:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install firebase-admin
      - run: node generate-rss-firebase.js
      - run: git config user.name "bot"
      - run: git config user.email "bot@email.com"
      - run: git add rss.xml
      - run: git commit -m "rss update" || exit 0
      - run: git push